package listing

import (
	"fmt"
	"regexp"
	"strings"
)

type RawListing struct {
	Title, Price, Condition, FrameSize, WheelSize, FrameMaterial, FrontTravel, RearTravel string
}

type Listing struct {
	Title, Year, Manufacturer, Price, Currency, Condition, FrameSize, WheelSize, FrameMaterial, FrontTravel, RearTravel string
}

func (l RawListing) Print() string {
	return fmt.Sprintf("Title: %s\nPrice: %s\n\tCondition: %s\n\tFrame Size: %s\n\tWheel Size: %s\n\tFront Travel: %s\n\tRear Travel: %s\n\tFrame Material: %s\n\t\n",
		l.Title, l.Price, l.Condition, l.FrameSize, l.WheelSize, l.FrontTravel, l.RearTravel, l.FrameMaterial)
}

func (l RawListing) PostProcess() Listing {
	newL := Listing{
		Title: l.Title,
		Year: extractYear(l.Title),
		Manufacturer: extractManufacturer(l.Title),
		Currency: extractCurrency(l.Price),
		Price: extractPrice(l.Price),
		Condition: l.Condition,
		FrameSize: l.FrameSize,
		WheelSize: l.WheelSize,
		FrontTravel: l.FrontTravel,
		RearTravel: l.RearTravel,
		FrameMaterial: l.FrameMaterial,
	}

	return newL
}

func extractYear(title string) string {
	reg := regexp.MustCompile(`\d{4}`)
	s := reg.FindString(title)
	return s
}

func extractCurrency(price string) string {
	reg := regexp.MustCompile(`(CAD|USD)`)
	return reg.FindString(price)
}

func extractPrice(price string) string {
	reg := regexp.MustCompile(`[0-9,]+`)
	return reg.FindString(price)
}

func extractManufacturer(title string) string {
	for _, manufacturer := range knownManufacturers {
		if strings.Contains(strings.ToLower(title), strings.ToLower(manufacturer)) {
			return manufacturer
		}
	}
	return ""
}

var knownManufacturers = []string{
    "3T",
    "6ku",
    "Alan Bike",
    "Alchemy Bikes",
    "Alex Singer",
    "All-City",
    "Allied Cycle Works",
    "Altruiste Bikes",
    "Argon 18",
    "Ascari Bicycles",
    "Avanti Bicycles",
    "Basso",
    "Battaglin",
    "Baum",
    "Bear Claw Bicycle Co.",
    "Beone",
    "Berthoud",
    "BH",
    "Bianchi",
    "Bike Friday",
    "Bilenky",
    "Bionicon",
    "Blue Competition Cycles",
    "BMC",
    "Bob Jackson",
    "Boardman",
    "Bombtrack",
    "Bottechia",
    "Breezer",
    "British Eagle",
    "Brodie",
    "Brompton",
    "BTR",
    "Buffalo",
    "Burley",
    "Cachet",
    "Caleti Cycles",
    "Calfee Design",
    "Cannondale",
    "Canyon",
    "Carrera Bicycles",
    "Casati",
    "Cervelo",
    "Chapter 2",
    "Chesini",
    "Chiru Endurance Bikes",
    "Cielo",
    "CIOCC",
    "Cinelli",
    "Cipollini",
    "Civia",
    "Colnago",
    "Columbine",
    "Commencal",
    "Co-Motion",
    "Corsa",
    "Corvid Cycles",
    "Cube Bikes",
    "Daccordi",
    "Dahon",
    "Davidson",
    "Dawes",
    "Decathalon",
    "De Rosa",
    "Diamondback",
    "Dimond",
    "Dioko",
    "DirtySixer",
    "Dosnoventa",
    "Dragon Bicycles",
    "Easy Racers",
    "Eddy Merckx",
    "Electra",
    "EMC",
    "Endorfin",
    "Erickson Bikes",
    "Everton",
    "Evil Bike Co.",
    "EVO",
    "Factor Bikes",
    "Factory",
    "Fairdale",
    "Firefly",
    "Felt",
    "Focus",
    "Fondriest",
    "Fortified",
    "Framed",
    "Franco Bicycles",
    "Frog",
    "Fuji",
    "Gary Fisher",
    "Gazelle",
    "Generic",
    "GHOST-bikes",
    "Giant",
    "Gilmour",
    "Giordano",
    "Gios",
    "Gitane",
    "Goku Cycles",
    "GreenSpeed",
    "GT",
    "Guerciotti",
    "Gunnar",
    "Haley Bicycles",
    "Hampsten",
    "Haro",
    "Hasa",
    "Hase Bicycles",
    "Head",
    "Hero",
    "Holland Cycles",
    "Huffy",
    "Hutch",
    "Ibis",
    "Ican",
    "Independent Fabrication",
    "I Stole.It",
    "JP Weigle",
    "Jamis",
    "Janssen",
    "Kemo",
    "Kent",
    "Kestrel",
    "KHS",
    "Kildemoes",
    "Klein Bikes",
    "Kona",
    "Kuota",
    "La Pierre",
    "Lauf",
    "Litespeed",
    "Liv",
    "Look",
    "Lynskey",
    "Marin",
    "Masi",
    "Merax",
    "Mercier",
    "Merida",
    "Merlin",
    "Micargi",
    "Milwaukee Bicycle",
    "Miyata",
    "Mondraker",
    "Mongoose",
    "Montague Bikes",
    "Moots",
    "Mosiac Cycles",
    "Motobecane",
    "Murray",
    "Mustang",
    "Nashbar",
    "Neil Pryde",
    "Nicolai",
    "Niner",
    "Nishiki",
    "No. 22 Bicycle Company",
    "Norco",
    "NS Bikes",
    "Nukeproof",
    "Ocoee",
    "Olmo",
    "Olympia",
    "Open Cycles",
    "Orbea",
    "Orro",
    "Otso Cycles",
    "Pace Cycles",
    "Parlee",
    "Pashley",
    "Peugeot",
    "Pinarello",
    "Pivot",
    "Polygon",
    "Pride Bikes",
    "Pure Cycles",
    "Quintanaroo",
    "Quiring",
    "Racycles",
    "Radon Bikes",
    "Ragley",
    "Raleigh",
    "Rans",
    "Redline",
    "Remot Bikes",
    "Renovo",
    "Retrospec",
    "Revel Bikes",
    "Ribble",
    "Ridgeback",
    "Ridley",
    "Ritchey",
    "Rivendell",
    "Rocky Mountain",
    "Rodriguez Bikes",
    "Rondo",
    "Rose",
    "Rossin",
    "Rotwild",
    "Roux",
    "Sage Titanium Bicycles",
    "Salsa",
    "S.A.M.’s Bike Company",
    "Santa Cruz",
    "Santana",
    "Saracen",
    "Savadeck",
    "Scapin",
    "Scattante",
    "Schindelhauer Bikes",
    "Schwinn",
    "SCO",
    "Scott",
    "Seven",
    "Shinola",
    "Skream",
    "Soma",
    "Specialized",
    "Spectrum",
    "Speedvagen",
    "Spicer Cycles",
    "Spot Cycles",
    "Stanridge Cycles",
    "Stanton Bikes",
    "Starling Cycles",
    "Stevens Bikes",
    "Stinner Frameworks",
    "Storck",
    "Stradalli",
    "Steppenwolf",
    "Surly",
    "T-Lab Bikes",
    "Taurus",
    "Tern",
    "Thesis",
    "Tifosi",
    "Time",
    "Tomasso",
    "Tommasini",
    "Torelli",
    "Trek",
    "Trinx",
    "Univega",
    "Upland",
    "Van Dessel",
    "Van Nicholas",
    "Viathon Bicycles",
    "Velovie",
    "Vilano",
    "Vynl Bikes",
    "Vitus",
    "Volae",
    "Why Cycles",
    "Whyte",
    "Wilier",
    "Yeti",
    "Zinn Cycles",
}