package listing

// MountainBikeType defines an enumeration of mountain bike types.
type MountainBikeType int

const (
	CrossCountry MountainBikeType = iota // CrossCountry represents bikes designed for efficiency and speed on varied terrain.
	Trail                                // Trail bikes are versatile, suitable for a wide range of terrain.
	Enduro                               // Enduro bikes are for aggressive riding on challenging terrains.
	Downhill                             // Downhill bikes are for steep, downhill terrains requiring high durability and suspension.
	AllMountain                          // AllMountain bikes are for general mountain biking, covering a broad range of riding styles.
	Electric                             // Electric mountain bikes are equipped with an electric motor to assist pedaling.
	Kids                                 // Kids bikes are designed for children.
	Hardtail                             // Hardtail bikes have a rigid frame with a front suspension fork.
	DirtJump                             // DirtJump bikes are for jumping and tricks on dirt tracks.
)

type BikeModel struct {
	Name    string
	Purpose MountainBikeType
}

var bikeModels = map[string][]BikeModel{
	"Ari": {
		{"La Sal Peak", Enduro},
		{"Timp Peak", Enduro}, // Electric Enduro
		{"Delano Peak", Enduro},
		{"Nebo Peak", AllMountain}, // Electric All Mountain
		{"Wiki Peak", Trail},
		{"Abajo Peak", Trail},
		{"Wire Peak 2.0", Trail},
		{"Cascade Peak", Trail},
		{"Signal Peak", CrossCountry},
		{"Solitude", CrossCountry},
		{"Wasatch Peak", CrossCountry},
		{"Dirt Jumper", DirtJump},
		{"Superior Peak", Downhill},
	},
	"Alchemy": {
		{"Arktos 125", Trail},
		{"Arktos 140", AllMountain},
		{"Arktos 150", Enduro},
		{"Argos", Trail},
		{"Argos Au", CrossCountry},
	},
	"Banshee": {
		{"Prime", Enduro},
		{"Titan", Enduro},
		{"Rune", Enduro},
		{"Phantom", AllMountain},
		{"Spitfire", Trail},
		{"Paradox", Hardtail},
		{"Enigma", Hardtail},
		{"Legend", Downhill},
	},
	"Bianchi": {
		{"Methanol CV FS", CrossCountry},
		{"Methanol CV RS", CrossCountry},
		{"Lynx", Trail},
		{"Nitron", Trail},
		{"Magma", Trail},
		{"Assoluto", CrossCountry},
	},
	"Canfield": {
		{"ONE.2", Downhill},
		{"Jedi", Downhill},
		{"Lithium", Enduro},
		{"Balance", Trail},
		{"Tilt", Trail},
		{"Yelli Screamy", Hardtail},
		{"Nimble 9", Hardtail},
	},
	"Cannondale": {
		{"Scalpel", CrossCountry},
		{"Scalpel HT", CrossCountry},
		{"Scalpel SE", CrossCountry},
		{"Habit", Trail},
		{"Habit HT", Trail},
		{"Jekyll", Enduro},
		{"Moterra", Electric},
		{"Trail SE", Trail},
		{"Trail", Trail},
	},
	"Canyon": {
		{"Spectral", Trail},
		{"Spectral:ON", Electric},
		{"Strive", Enduro},
		{"Torque", Enduro},
		{"Sender", Downhill},
		{"Neuron", Trail},
		{"Grand Canyon", CrossCountry},
		{"Exceed", CrossCountry},
		{"Lux Trail", CrossCountry},
		{"Lux World Cup", CrossCountry},
	},
	"Chromag": {
		{"Darco", Trail},
		{"Darco Ti", Trail},
		{"Lowdown", Hardtail},
		{"Rootdown", Hardtail},
		{"Rootdown BA", Hardtail},
		{"Rootdown Ti", Hardtail},
		{"Stylus", Hardtail},
		{"Wideangle", Hardtail},
		{"Monk", Hardtail},
		{"Minor Threat", Kids},
		{"Surface", AllMountain},
		{"Surface Voyager", AllMountain},
		{"Primer", AllMountain},
		{"Doctahawk", Downhill},
		{"Samaritan", AllMountain},
	},
	"Commencal": {
		{"Meta TR", Trail},
		{"Meta AM", AllMountain},
		{"Meta SX", Enduro},
		{"Meta HT", Hardtail},
		{"Meta V5", Trail},
		{"Meta Power", Electric},
		{"TR Meta", Trail},
		{"AM Meta", AllMountain},
		{"SX Meta", Enduro},
		{"HT Meta", Hardtail},
		{"Power Meta", Electric},
		{"Clash", Enduro},
		{"Supreme DH", Downhill},
		{"Frs", Downhill},
		{"Tempo", Trail},
		{"Absolut", Hardtail},
	},
	"Cube": {
		{"Stereo", Trail},
		{"Stereo Hybrid", Electric},
		{"Reaction", CrossCountry},
		{"Reaction Hybrid", Electric},
		{"Stereo ONE", Enduro},
		{"Two15", Downhill},
		{"AMS", CrossCountry},
		{"Elite", CrossCountry},
		{"Attention", Hardtail},
		{"Aim", Hardtail},
		{"Nutrail Hybrid", Electric},
		{"Access", CrossCountry},
	},
	"Deviate": {
		{"Highlander", Enduro},
		{"Highlander Mullet", Enduro},
		{"Claymore", Enduro},
		{"Guide", Trail},
	},
	"Devinci": {
		{"Spartan", Enduro},
		{"Troy", AllMountain},
		{"Django", Trail},
		{"Marshall", Hardtail},
		{"Hatchet", Hardtail},
		{"Wilson", Downhill},
		{"Frantik", DirtJump},
		{"Kobain", Trail},
	},
	"Diamondback": {
		{"Release", Trail},
		{"Catch", Enduro},
		{"Line", Downhill},
		{"Sync'r", CrossCountry},
		{"Overdrive", Hardtail},
		{"Hook", Hardtail},
		{"Yowie", CrossCountry},
	},
	"Evil": {
		{"Insurgent", Enduro},
		{"Offering", Trail},
		{"Following", Trail},
		{"Wreckoning", AllMountain},
		{"The Calling", Downhill},
		{"Epocalypse", Electric},
		{"Faction", DirtJump},
	},
	"Felt": {
		{"Edict", CrossCountry},
		{"Edict Advanced", CrossCountry},
		{"Doctrine", Downhill},
		{"Compulsion", Enduro},
		{"Virtue", Trail},
	},
	"Fezzari": {
		{"La Sal Peak", Enduro},
		{"Timp Peak", Enduro}, // Electric Enduro
		{"Delano Peak", Enduro},
		{"Nebo Peak", AllMountain}, // Electric All Mountain
		{"Wiki Peak", Trail},
		{"Abajo Peak", Trail},
		{"Wire Peak 2.0", Trail},
		{"Cascade Peak", Trail},
		{"Signal Peak", CrossCountry},
		{"Solitude", CrossCountry},
		{"Wasatch Peak", CrossCountry},
		{"Dirt Jumper", DirtJump},
		{"Superior Peak", Downhill},
	},
	"Forbidden": {
		{"Druid", Trail},
		{"Dreadnought", Enduro},
		{"Supernought", Downhill},
	},
	"Gary Fisher": {},
	"Ghost-Bikes": {
		{"SL AMR", Trail},
		{"SL AMR X", AllMountain},
		{"Riot", Enduro},
		{"FR AMR", Enduro},
		{"Kato", CrossCountry},
		{"Lector", CrossCountry},
		{"Hybride Kato", Electric},
		{"Hybride SL AMR", Electric},
		{"Asket", Downhill},
	},
	"Giant": {
		{"Trance X", Trail},
		{"Trance X Advanced E+", Electric},
		{"Reign", Enduro},
		{"Reign E+", Electric},
		{"Glory", Downhill},
		{"Stance", Trail},
		{"Stance E+", Electric},
		{"Anthem", CrossCountry},
		{"Talon", Hardtail},
		{"Fathom", Hardtail},
	},
	"GT": {
		{"Force", Enduro},
		{"Sensor", Trail},
		{"Zaskar", CrossCountry},
		{"Fury", Downhill},
		{"La Bomba", DirtJump},
		{"Aggressor", Hardtail},
		{"Avalanche", Hardtail},
	},
	"Guerrilla Gravity": {
		{"Smash", Enduro},
		{"Megatrail", Enduro},
		{"Trail Pistol", Trail},
		{"Shred Dogg", Hardtail},
		{"The Gnarvana", Hardtail},
	},
	"Haibike": {
		{"AllMtn", Electric},
		{"AllTrail", Electric},
		{"Lyke", Electric},
		{"FullSeven", Electric},
		{"HardSeven", Electric},
		{"Nduro", Electric},
		{"Xduro", Electric},
	},
	"Haro": {
		{"Shift Plus i/O 5", Electric},
		{"Double Peak", Trail},
		{"Double Peak 29", Trail},
		{"Shift R7 Plus", Hardtail},
		{"Shift R5", Hardtail},
		{"Flightline", Downhill},
	},
	"Huffy": {
		{"Stone Mountain", Hardtail},
		{"Hardtail Mountain Bike", Hardtail},
		{"Caromont", Hardtail},
		{"Summit Ridge", Hardtail},
		{"Alpine", Hardtail},
	},
	"Ibis": {
		{"Ripmo", Trail},
		{"Ripmo AF", Trail},
		{"Mojo", Trail},
		{"Mojo HD5", Enduro},
		{"Exie", CrossCountry},
		{"Oso", Electric},
	},
	"Intense": {
		{"Tracer", Enduro},
		{"Carbine", Enduro},
		{"Primer", Trail},
		{"Tazer", Electric},
		{"Sniper", CrossCountry},
	},
	"Jamis": {
		{"Hardline", Enduro},
		{"Portal", Trail},
		{"Dakar", CrossCountry},
		{"Komodo", Hardtail},
		{"Dragonfly", CrossCountry},
	},
	"Juliana": {
		{"Roubion", Enduro},
		{"Strega", Enduro},
		{"Furtado", Trail},
		{"Joplin", CrossCountry},
		{"Maverick", Trail},
	},
	"KHS": {
		{"Team SX", Downhill},
		{"DH 650", Downhill},
		{"Aguila", Trail},
		{"SixFifty 650B", Trail},
		{"SixFifty 29er", Trail},
	},
	"Knolly": {
		{"Warden", Enduro},
		{"Fugitive", Enduro},
		{"Endorphin", Trail},
		{"Chilcotin", AllMountain},
		{"Cache", Trail},
	},
	"Kona": {
		{"Process X", Enduro},
		{"Process 153", Enduro},
		{"Honzo", Hardtail},
		{"Hei Hei", Trail},
		{"Remote", Electric},
		{"Operator", Downhill},
		{"Unit X", Hardtail},
		{"Hei Hei Trail", Trail},
	},
	"Litespeed": {
		{"Pinhoti III", CrossCountry},
	},
	"Liv": {
		{"Intrigue", Trail},
		{"Intrigue X Advanced E+", Electric},
		{"Hail", Enduro},
		{"Hail Advanced", Enduro},
		{"Embolden", Trail},
		{"Embolden E+", Electric},
		{"Pique", CrossCountry},
		{"Pique Advanced Pro", CrossCountry},
		{"Tempt", Trail},
	},
	"Marin": {
		{"Alpine Trail", Trail},
		{"Hawk Hill", Trail},
		{"Mount Vision", Trail},
		{"Rift Zone", CrossCountry},
		{"San Quentin", Hardtail},
		{"Bobcat Trail", Hardtail},
		{"Pine Mountain", Hardtail},
	},
	"Mondraker": {
		{"Summum Carbon", Downhill},
		{"SuperFoxy Carbon", Enduro},
		{"Foxy Carbon", Enduro},
		{"Dune Carbon", Enduro},
		{"Crafty Carbon", Electric},
		{"Level", Electric},
		{"Chrono", CrossCountry},
		{"Factor", CrossCountry},
	},
	"Mongoose": {
		{"Salvo", Trail},
		{"Legion", Trail},
		{"Fireball", DirtJump},
		{"Tyax", Hardtail},
	},
	"Motobecane": {},
	"Murray": {
		{"Monterey", Hardtail},
		{"Wildwood", Hardtail},
		{"Ridge Master", Hardtail},
	},
	"Nashbar": {
		{"ATB 29er", Hardtail},
		{"Carbon 29er", Hardtail},
		{"Single Speed 29er", Hardtail},
		{"Women's ATB 29er", Hardtail},
	},
	"Nicolai": {
		{"Geometron G1", Downhill},
		{"Geometron G16", Enduro},
		{"Geometron G13", Enduro},
		{"G19", Enduro},
		{"Nucleon 16", Enduro},
		{"Nucleon 12", Trail},
		{"Saturn 14", Trail},
		{"Argon FR", Enduro},
		{"Argon AM", AllMountain},
		{"Argon TR", Trail},
		{"Argon CX", CrossCountry},
	},
	"Niner": {
		{"RIP 9 RDO", Enduro},
		{"JET 9 RDO", CrossCountry},
		{"WFO 9 RDO", Enduro},
		{"SIR 9", Hardtail},
	},
	"Nishiki": {
		{"Colorado Comp", Hardtail},
		{"Pueblo", Hardtail},
		{"Colorado", Hardtail},
	},
	"Norco": {
		{"Range", Enduro},
		{"Sight", Trail},
		{"Shore", Enduro},
		{"Storm", Hardtail},
		{"Fluid", Trail},
		{"Revolver", Hardtail},
		{"Optic", CrossCountry},
		{"Torrent", Hardtail},
	},
	"NS Bikes": {
		{"Define", Trail},
		{"Eccentric", AllMountain},
		{"Soda Slope", DirtJump},
		{"Metropolis", DirtJump},
		{"Suburban", DirtJump},
		{"Movement", DirtJump},
	},
	"Nukeproof": {
		{"Mega", Enduro},
		{"Giga", Enduro},
		{"Scout", Trail},
		{"Reactor", Trail},
		{"Cub-Scout", Kids},
	},
	"Orange": {
		{"Alpine 6", Enduro},
		{"Stage 6", Enduro},
		{"Switch 6", Enduro},
		{"Switch 7", Enduro},
		{"Satsuma", Trail},
		{"Patriot", Electric},
		{"Phase", Electric},
		{"Five", Trail},
		{"Crush", Hardtail},
		{"P7", Hardtail},
		{"Clockwork", Hardtail},
	},
	"Orbea": {
		{"Rallon", Enduro},
		{"Occam", Trail},
		{"Oiz", CrossCountry},
		{"Rise", Electric},
		{"Onna", Electric},
	},
	"Pivot": {
		{"Firebird", Enduro},
		{"Switchblade", Trail},
		{"Mach 4 SL", CrossCountry},
		{"Mach 5.5", Trail},
		{"Mach 6", AllMountain},
		{"Trail 429", Trail},
		{"Shuttle", Electric},
		{"LES", Hardtail},
		{"Shadowcat", Trail},
	},
	"Pole": {
		{"EVOLINK 140", Trail},
		{"EVOLINK 158", Enduro},
		{"STAHLWERK EVO", Enduro},
		{"MACHINE", Downhill},
	},
	"Polygon": {
		{"Siskiu T", Trail},
		{"Siskiu T8", Enduro},
		{"Siskiu D", Downhill},
		{"Collosus", Downhill},
		{"Xquarone", CrossCountry},
		{"Cascade", Trail},
		{"Bend R", Hardtail},
		{"Bend RV", Hardtail},
	},
	"Propain": {
		{"Tyee", Enduro},
		{"Spindrift", Enduro},
		{"Hugene", Trail},
		{"Rage", Downhill},
		{"Ekano", Electric},
		{"Yuma", Kids},
	},
	"Raleigh": {
		{"Tokul", Trail},
		{"Talus", Hardtail},
		{"Kodiak", Hardtail},
		{"Tekoa", Hardtail},
		{"Tokul IE", Electric},
	},
	"Reeb": {
		{"Sqweeb", AllMountain},
		{"Donkadonk", Enduro},
	},
	"Revel": {
		{"Rail", Enduro},
		{"Rascal", Trail},
		{"Ranger", CrossCountry},
	},
	"Rocky Mountain": {
		{"Altitude", Trail},
		{"Altitude Powerplay", Electric},
		{"Instinct", Trail},
		{"Instinct Powerplay", Electric},
		{"Slayer", Enduro},
		{"Element", CrossCountry},
		{"Growler", Hardtail},
		{"Thunderbolt", Trail},
		{"Pipeline", Enduro},
	},
	"RSD": {
		{"Wildcat", Trail},
		{"MiddleChild", Hardtail},
		{"The Sheriff", Hardtail},
		{"Mayor", Hardtail},
		{"Sergeant", Hardtail},
		{"RS-291", Hardtail},
		{"RS 291", Hardtail},
	},
	"Salsa": {
		{"Timberjack", Hardtail},
		{"Blackthorn", Hardtail},
		{"Horsethief", Trail},
		{"Spearfish", CrossCountry},
	},
	"Santa Cruz": {
		{"Bullit", Electric},
		{"Megatower", Enduro},
		{"Mega tower", Enduro},
		{"Hightower", AllMountain},
		{"High tower", AllMountain},
		{"Heckler", Trail},
		{"Nomad", Enduro},
		{"Tallboy", Trail},
		{"Blur", CrossCountry},
		{"5010", Trail},
		{"Bronson", AllMountain},
		{"Chameleon", Hardtail},
		{"V10", Downhill},
		{"Jackal", DirtJump},
	},
	"Scor": {
		{"4060 LT", Enduro},
		{"4060 ST", Trail},
		{"4060 Z", Enduro},
		{"4060 Z ST", Enduro},
		{"4060 Z LT", Enduro},
	},
	"Scott": {
		{"Ransom", Enduro},
		{"Genius", Trail},
		{"Spark", CrossCountry},
		{"Scale", CrossCountry},
		{"Contessa", CrossCountry},
		{"Gambler", Downhill},
		{"Voltage FR", Downhill},
		{"Voltage YZ", DirtJump},
		{"Patron", Electric},
	},
	"Specialized": {
		{"Demo", Downhill},
		{"Stumpjumper EVO", Enduro},
		{"Enduro", AllMountain},
		{"Status", Trail},
		{"Turbo Levo", Electric},
		{"Kenevo", Electric},
		{"Epic", CrossCountry},
		{"Chisel", Hardtail},
		{"Fuse", Hardtail},
		{"Rockhopper", Hardtail},
	},
	"Surly": {
		{"Instigator", Hardtail},
		{"Karate Monkey", Hardtail},
		{"Krampus", Hardtail},
	},
	"Transition": {
		{"Patrol", Enduro},
		{"Sentinel", AllMountain},
		{"Scout", Trail},
		{"Spire", CrossCountry},
		{"Smuggler", Trail},
		{"Covert", Hardtail},
		{"PBJ", DirtJump},
		{"TR11", Downhill},
		{"Throttle", Electric},
		{"Repeater", Electric},
	},
	"Trek": {
		{"Slash", Enduro},
		{"Remedy", AllMountain},
		{"Fuel EX", Trail},
		{"Top Fuel", CrossCountry},
		{"Supercaliber", CrossCountry},
		{"Powerfly FS", Electric},
		{"Powerfly HT", Electric},
		{"Roscoe", Hardtail},
		{"Marlin", Hardtail},
		{"Session", Downhill},
	},
	"Vitus": {
		{"Escarpe", Trail},
		{"Mythique", AllMountain},
		{"Sommet", Enduro},
		{"Dominer", Downhill},
		{"Nucleus", Hardtail},
		{"Sentier", Hardtail},
		{"E-Sommet", Electric},
	},
	"We Are One": {
		{"Arrival", Enduro},
		{"Revive", Trail},
		{"Convergence", AllMountain},
	},
	"WAO": {
		{"Arrival", Enduro},
		{"Revive", Trail},
		{"Convergence", AllMountain},
	},
	"WR1": {
		{"Arrival", Enduro},
		{"Revive", Trail},
		{"Convergence", AllMountain},
	},
	"Whyte": {
		{"E-160", Electric},
		{"E-150", Electric},
		{"E-180 RS", Electric},
		{"G-170 S", Enduro},
		{"G-170C", Enduro},
		{"S-150", Trail},
		{"T-140", Trail},
		{"T-130", Trail},
		{"S-120", Trail},
		{"905", Hardtail},
		{"901", Hardtail},
		{"605", Hardtail},
	},
	"Yeti": {
		{"SB120", Trail},
		{"SB 120", Trail},
		{"SB165", Enduro},
		{"SB160", Enduro},
		{"SB150", Enduro},
		{"SB140", Trail},
		{"SB130", Trail},
		{"SB 165", Enduro},
		{"SB 160", Enduro},
		{"SB 150", Enduro},
		{"SB 140", Trail},
		{"SB 130", Trail},
		{"ASR", CrossCountry},
		{"SB 5.5", AllMountain},
		{"SB5.5", AllMountain},
		{"ARC", CrossCountry},
		{"160E", Electric},
	},
	"YT": {
		{"Capra", Enduro},
		{"Capra Core", Enduro},
		{"Deco", Enduro},
		{"Jeffsy", AllMountain},
		{"Izzo", Trail},
		{"Dirt Love", DirtJump},
	},
}

var knownManufacturers = []string{
	"Ari",
	"Alchemy",
	"Banshee",
	"Bianchi",
	"Canfield",
	"Cannondale",
	"Canyon",
	"Chromag",
	"Commencal",
	"Cube",
	"Deviate",
	"Devinci",
	"Diamondback",
	"Evil Bike Co.",
	"Evil",
	"Felt",
	"Fezzari",
	"Forbidden",
	"Gary Fisher",
	"GHOST-bikes",
	"Giant",
	"GT",
	"Guerilla Gravity",
	"Haibike",
	"Haro",
	"Huffy",
	"Ibis",
	"Intense",
	"Jamis",
	"Juliana",
	"KHS",
	"Knolly",
	"Kona",
	"Litespeed",
	"Liv",
	"Marin",
	"Mondraker",
	"Mongoose",
	"Motobecane",
	"Murray",
	"Nashbar",
	"Nicolai",
	"Niner",
	"Nishiki",
	"Norco",
	"NS Bikes",
	"Nukeproof",
	"Orange",
	"Orbea",
	"Pivot",
	"Pole",
	"Polygon",
	"Propain",
	"Raleigh",
	"Reeb",
	"Revel Bikes",
	"Revel",
	"Rocky Mountain",
	"RSD",
	"Salsa",
	"Santa Cruz",
	"Scor",
	"Scott",
	"Specialized",
	"Surly",
	"Transition",
	"Trek",
	"Vitus",
	"We Are One",
	"Whyte",
	"WR1",
	"Yeti",
	"YT",
	"YT Industries",
}
